
/// @file   Type_define.h
/// @date   2012/02/14
/// @author jinhwa Lee
/// @brief  기본적인 Define 정의 파일

/***********************************************************************/
/*                                                                     */
/*  FILE        :typedefine.h                                          */
/*  DATE        :Mon, Aug 22, 2011                                     */
/*  DESCRIPTION :define scalar types.                                  */
/*  CPU GROUP   :36C                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/

/*************************************************
* COMPILER for R8C/Tiny
*
* Copyright (C) 2004 (2010) Renesas Electronics Corporation.
* and Renesas Solutions Corporation. All rights reserved.
*
* typedef for startup
*
* $Date: 2005/11/01 04:31:54 $
* $Revision: 1.4 $
************************************************/
#ifndef __TYPE_DEFINE_H__
#define __TYPE_DEFINE_H__

#define true      1 
#define false     0
#define TRUE      1
#define FALSE     0

#define ON        1
#define OFF       0

#define ENABLE    1
#define DISABLE   0

#define SET       1
#define CLEAR     0

#define NULL        0
#define INDEX_ZERO  0
#define ZERO        0

#define RETURN_FALSE 0xFF


typedef char   S8;              ///< 8bit
typedef short  S16;             ///< 16bit
typedef long   S32;             ///< 32bit
typedef unsigned char   U8;     ///< 8bit
typedef unsigned short  U16;    ///< 16bit
typedef unsigned long   U32;    ///< 32bit

/// @brief Byte Union
typedef union{
  /// Bit Control
  struct{
    U8 b0:1;
    U8 b1:1;
    U8 b2:1;
    U8 b3:1;
    U8 b4:1;
    U8 b5:1;
    U8 b6:1;
    U8 b7:1;
  }bit;
  /// Byte Control
  U8 all;
}byte_dt;

typedef unsigned char HANDLE;  ///< TimeOut Handle

#endif    // #ifndef __TYPE_DEFINE_H__

