/***********************************************************************/
/*                                                                     */
/*  FILE        :cstartdef.h                                           */
/*  DATE        :Fri, Dec 16, 2011                                     */
/*  DESCRIPTION :define the size of stack.                             */
/*  CPU GROUP   :36C                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
#define __STACKSIZE__    0x200       // user stack
#define __ISTACKSIZE__   0x200        // interrupt stack
#define __HEAPSIZE__     0x0         // heap size
#define __STANDARD_IO__  0 			 // use standard I/O (ex printf)
#define __WATCH_DOG__    1 			 // When watchdog is made effective after reset, here is set to 1.
